name: frivillighed_rfam
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hovering: ^1.0.4
  provider: ^6.1.2
  cloud_firestore: ^4.17.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
