// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SqvcvasqfPo1XK6vyLMEVYVB2GIUig4',
    appId: '1:741558367057:web:70d203a1b7cc6700721970',
    messagingSenderId: '741558367057',
    projectId: 'frivillighed-rfa',
    authDomain: 'frivillighed-rfa.firebaseapp.com',
    storageBucket: 'frivillighed-rfa.appspot.com',
    measurementId: 'G-E34N8WF4V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlfRZsioom2UeBjVHIUPGO91LkAUg_te0',
    appId: '1:741558367057:android:01e808dd235a1c0f721970',
    messagingSenderId: '741558367057',
    projectId: 'frivillighed-rfa',
    storageBucket: 'frivillighed-rfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu6iG1zT5gyIIWSNhuXMg9psz2IOfJa3w',
    appId: '1:741558367057:ios:3471508aefd71f02721970',
    messagingSenderId: '741558367057',
    projectId: 'frivillighed-rfa',
    storageBucket: 'frivillighed-rfa.appspot.com',
    iosBundleId: 'com.example.frivillighedRfam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu6iG1zT5gyIIWSNhuXMg9psz2IOfJa3w',
    appId: '1:741558367057:ios:3471508aefd71f02721970',
    messagingSenderId: '741558367057',
    projectId: 'frivillighed-rfa',
    storageBucket: 'frivillighed-rfa.appspot.com',
    iosBundleId: 'com.example.frivillighedRfam',
  );
}
